### ISSUE TITLE
BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Madness0105** [TNT10128/mStats#6]
BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!BOT CANT RUN ON WINDOWS!!!!!!!!!!!!!!!

**Comment by tnt10128** [comment]
Please recreate your issue with the proper details, including error logs and how to reproduce the issue.
